# permissions for end users to view gomongoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gomongo-viewer-role
rules:
- apiGroups:
  - ocp4ee.ocp4.example
  resources:
  - gomongoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocp4ee.ocp4.example
  resources:
  - gomongoes/status
  verbs:
  - get
