# permissions for end users to edit gomongoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gomongo-editor-role
rules:
- apiGroups:
  - ocp4ee.ocp4.example
  resources:
  - gomongoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocp4ee.ocp4.example
  resources:
  - gomongoes/status
  verbs:
  - get
